# Generated by Django 5.0 on 2023-12-17 00:43

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='useraccount',
            name='account_type',
            field=models.CharField(choices=[('USER', 'USER'), ('COMPANY', 'COMPANY')], default='USER', max_length=10),
        ),
    ]
