# Generated by Django 5.0 on 2023-12-17 10:26

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('users', '0002_useraccount_account_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='useraccount',
            name='account_type',
            field=models.CharField(choices=[('USER', 'USER'), ('COMPANY', 'COMPANY')], max_length=20),
        ),
    ]
