# Generated by Django 5.0 on 2023-12-17 10:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_alter_useraccount_account_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='useraccount',
            name='account_type',
            field=models.CharField(choices=[(1, 'USER'), (2, 'COMPANY')], max_length=20),
        ),
        migrations.AlterField(
            model_name='useraccount',
            name='num_of_available_companies',
            field=models.PositiveIntegerField(choices=[(1, 'USER'), (2, 'COMPANY')], default=1),
        ),
    ]
