# Generated by Django 4.2.7 on 2023-11-28 00:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('offer', '0005_alter_joboffer_company'),
        ('users', '0003_alter_company_addresses'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Company',
        ),
    ]
