# Generated by Django 4.2.7 on 2023-11-28 22:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_delete_company'),
    ]

    operations = [
        migrations.AddField(
            model_name='useraccount',
            name='num_of_available_companies',
            field=models.IntegerField(default=1),
        ),
    ]
