# Generated by Django 5.0 on 2023-12-17 11:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_alter_useraccount_account_type_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='useraccount',
            name='account_type',
            field=models.CharField(choices=[(1, 'USER'), (2, 'COMPANY')], default=1, max_length=20),
        ),
    ]
