# Generated by Django 5.0 on 2023-12-17 11:57

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('users', '0005_alter_useraccount_account_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='useraccount',
            name='account_type',
            field=models.CharField(choices=[('USER', 'USER'), ('USER', 'COMPANY')], default='USER', max_length=20),
        ),
        migrations.AlterField(
            model_name='useraccount',
            name='num_of_available_companies',
            field=models.PositiveIntegerField(choices=[('USER', 'USER'), ('USER', 'COMPANY')], default=1),
        ),
    ]
