# Generated by Django 5.0 on 2023-12-19 01:36

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('users', '0006_alter_useraccount_account_type_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='useraccount',
            name='num_of_available_companies',
        ),
        migrations.AlterField(
            model_name='useraccount',
            name='account_type',
            field=models.CharField(choices=[('USER', 'USER'), ('COMPANY', 'COMPANY')], default='USER', max_length=20),
        ),
    ]
