# Generated by Django 4.2.7 on 2023-11-29 21:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Package',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('price_pln', models.DecimalField(decimal_places=2, max_digits=10)),
                ('stripe_price_id_pln', models.CharField(max_length=500)),
                ('price_euro', models.DecimalField(decimal_places=2, max_digits=10)),
                ('stripe_price_id_euro', models.CharField(max_length=500)),
                ('has_bumps', models.BooleanField(default=False)),
                ('num_of_bumps', models.IntegerField(default=0)),
                ('num_of_days_available', models.IntegerField(default=0)),
            ],
        ),
    ]
