# Generated by Django 5.0 on 2023-12-29 00:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0002_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='product',
            options={'ordering': ['price_euro'], 'verbose_name': 'Product', 'verbose_name_plural': 'Products'},
        ),
    ]
