# Generated by Django 4.2.7 on 2023-11-26 14:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('location', '0003_address'),
        ('users', '0003_alter_company_addresses'),
    ]

    operations = [
        migrations.CreateModel(
            name='EmploymentType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Experience',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Salary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('salary_from', models.FloatField()),
                ('salary_to', models.FloatField()),
                ('currency', models.CharField(choices=[('PLN', 'PLN'), ('EURO', 'EURO'), ('USD', 'USD')], max_length=10)),
                ('schedule', models.CharField(choices=[('MONTHLY', 'MONTHLY'), ('YEARLY', 'YEARLY'), ('WEEKLY', 'WEEKLY'), ('DAILY', 'DAILY'), ('HOURLY', 'HOURLY')], max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='WorkType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='JobOffer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('description', models.TextField(blank=True, max_length=1000, null=True)),
                ('is_remote', models.BooleanField(default=False)),
                ('is_hybrid', models.BooleanField(default=False)),
                ('skills', models.CharField(blank=True, max_length=100, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('is_archived', models.BooleanField(default=False)),
                ('adresses', models.ManyToManyField(blank=True, to='location.address')),
                ('company', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='users.company')),
                ('employment_type', models.ManyToManyField(blank=True, to='offer.employmenttype')),
                ('experience', models.ManyToManyField(blank=True, to='offer.experience')),
                ('salary', models.ManyToManyField(blank=True, to='offer.salary')),
                ('work_type', models.ManyToManyField(blank=True, to='offer.worktype')),
            ],
        ),
    ]
