# Generated by Django 5.0 on 2023-12-09 12:56

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('offer', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='joboffer',
            name='is_active',
        ),
        migrations.AddField(
            model_name='joboffer',
            name='status',
            field=models.CharField(
                choices=[('DRAFT', 'DRAFT'), ('PENDING', 'PENDING'), ('ACTIVE', 'ACTIVE'), ('EXPIRED', 'EXPIRED')],
                default='DRAFT', max_length=10),
        ),
    ]
