# Generated by Django 5.0 on 2023-12-27 01:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('offer', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='salary',
            name='currency',
            field=models.CharField(blank=True, choices=[('PLN', 'PLN'), ('EURO', 'EURO'), ('USD', 'USD')], max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='salary',
            name='salary_from',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='salary',
            name='salary_to',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='salary',
            name='schedule',
            field=models.CharField(blank=True, choices=[('MONTHLY', 'MONTHLY'), ('YEARLY', 'YEARLY'), ('WEEKLY', 'WEEKLY'), ('DAILY', 'DAILY'), ('HOURLY', 'HOURLY')], max_length=10, null=True),
        ),
    ]
