# Generated by Django 4.2.7 on 2023-11-26 14:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('offer', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='joboffer',
            name='company_logo',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='joboffer',
            name='company_name',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='joboffer',
            name='is_scraped',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='joboffer',
            name='url',
            field=models.URLField(blank=True, null=True),
        ),
    ]
