# Generated by Django 4.2.7 on 2023-11-29 21:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0002_package'),
        ('offer', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='joboffer',
            name='is_archived',
        ),
        migrations.AddField(
            model_name='joboffer',
            name='package',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='payment.package'),
        ),
    ]
