# Generated by Django 4.2.7 on 2023-11-26 15:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('offer', '0002_joboffer_company_logo_joboffer_company_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employmenttype',
            name='name',
            field=models.CharField(max_length=50, unique=True),
        ),
        migrations.AlterField(
            model_name='experience',
            name='name',
            field=models.CharField(max_length=50, unique=True),
        ),
        migrations.AlterField(
            model_name='worktype',
            name='name',
            field=models.CharField(max_length=50, unique=True),
        ),
    ]
