# Generated by Django 5.0 on 2024-01-05 18:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('offer', '0002_alter_salary_currency_alter_salary_salary_from_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='joboffer',
            name='apply_form',
            field=models.URLField(blank=True, default=None, null=True),
        ),
    ]
