# Generated by Django 5.0 on 2023-12-09 12:59

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('offer', '0002_remove_joboffer_is_active_joboffer_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='joboffer',
            name='title',
            field=models.CharField(max_length=100),
        ),
    ]
