# Generated by Django 5.0 on 2023-12-17 11:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('offer', '0003_alter_joboffer_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='joboffer',
            name='slug',
            field=models.SlugField(default=11, unique=True),
            preserve_default=False,
        ),
    ]
