# Generated by Django 4.2.7 on 2023-11-26 21:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('offer', '0003_alter_employmenttype_name_alter_experience_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='joboffer',
            name='description',
            field=models.TextField(blank=True, max_length=5000, null=True),
        ),
    ]
