# Generated by Django 5.0 on 2024-01-08 02:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('offer', '0004_jobofferrate'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='jobofferrate',
            options={'ordering': ['-rate'], 'verbose_name': 'Job Offer Rate', 'verbose_name_plural': 'Job Offer Rates'},
        ),
        migrations.AddField(
            model_name='jobofferrate',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
