# Generated by Django 4.2.7 on 2023-11-28 21:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('offer', '0005_alter_joboffer_company'),
    ]

    operations = [
        migrations.AddField(
            model_name='joboffer',
            name='apply_form',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='joboffer',
            name='days_until_expiration',
            field=models.IntegerField(default=30),
        ),
    ]
