# Generated by Django 5.0 on 2024-01-04 21:41

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('candidates', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='candidate',
            name='cv',
            field=models.FileField(blank=True, null=True, upload_to='cv', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['pdf'], message='Only PDF file is allowed')]),
        ),
    ]
