# Generated by Django 5.0 on 2024-01-04 22:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('candidates', '0002_candidate_cv'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='candidate',
            name='company',
        ),
    ]
