# Generated by Django 4.2.7 on 2023-11-29 01:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('candidate', '0001_initial'),
        ('location', '0001_initial'),
        ('offer', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='offercandidate',
            name='offer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='offer.joboffer'),
        ),
        migrations.AddField(
            model_name='candidate',
            name='address',
            field=models.ManyToManyField(blank=True, to='location.address'),
        ),
        migrations.AddField(
            model_name='candidate',
            name='offer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='offer.joboffer'),
        ),
    ]
