# Generated by Django 4.2.7 on 2023-11-29 01:35

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('offer', '0007_rename_adresses_joboffer_addresses'),
        ('candidate', '0002_offercandidate_delete_candidate'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='OfferCandidate',
            new_name='Candidate',
        ),
    ]
