# Generated by Django 4.2.7 on 2023-11-29 13:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('candidate', '0003_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='candidate',
            name='status',
            field=models.CharField(choices=[('Pending', 'Pending'), ('Reviewed', 'Reviewed'), ('Rejected', 'Rejected')], default=1, max_length=20),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='OfferCandidate',
        ),
    ]
