# Generated by Django 5.0 on 2023-12-09 08:55

import django.core.validators
from django.db import migrations, models

import candidate.models


class Migration(migrations.Migration):
    dependencies = [
        ('candidate', '0003_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='candidate',
            name='resume',
            field=models.FileField(blank=True, upload_to='', validators=[
                django.core.validators.FileExtensionValidator(allowed_extensions=['pdf'],
                                                              message='Only PDF files are allowed'),
                candidate.models.validate_file_size]),
        ),
    ]
