# Generated by Django 4.2.7 on 2023-11-30 12:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('candidate', '0004_candidate_status_delete_offercandidate'),
    ]

    operations = [
        migrations.AddField(
            model_name='candidate',
            name='resume',
            field=models.FileField(default=1, upload_to=''),
            preserve_default=False,
        ),
    ]
