# Generated by Django 4.2.7 on 2023-11-28 22:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('location', '0003_address'),
        ('company', '0002_company_facebook_url_company_instagram_url_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='addresses',
            field=models.ManyToManyField(blank=True, to='location.address'),
        ),
    ]
