# Generated by Django 5.0 on 2024-01-07 15:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0004_alter_company_logo'),
    ]

    operations = [
        migrations.CreateModel(
            name='CompanyCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
            ],
            options={
                'verbose_name': 'Company Category',
                'verbose_name_plural': 'Company Categories',
                'ordering': ['name'],
            },
        ),
    ]
