# Generated by Django 5.0 on 2024-02-27 21:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('favourite', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='favourite',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
